### ISSUE TITLE
Publish artifacts on CI

### ISSUE THREAD

**Issue by gongminmin** [Microsoft/ShaderConductor#11]
Generate artifacts by CI system, and publish them.

**Comment by Zingam** [comment]
Great! Please, do this sooner!

**Comment by gongminmin** [comment]
The first artifact built by appveyor came out: https://ci.appveyor.com/project/gongminmin/shaderconductor/builds/20370601/artifacts

**Comment by Zingam** [comment]
@gongminmin Cool! Thank you! Please add a link to the artifacts in the README.md so that people can find the artifacts easier.

**Comment by gongminmin** [comment]
Done
