### ISSUE TITLE
Investigate why dxcompiler file is so large on Linux and macOS

### ISSUE THREAD

**Issue by gongminmin** [microsoft/ShaderConductor#19]
dxcompiler.dll is 17.7MB (7.7MB compressed), but libdxcompiler.so is 34.5MB (13.1MB compressed), and libdxcompiler.dylib is 27.1MB (10.0MB compressed). Need to have some understanding about why they are so different, and how to improve this.

**Comment by Jjagg** [comment]
The MinSizeRel configuration makes a big difference.
In a custom build on my Linux machine from aebd3e66f191530a8b6b1a34c30ae4d9409d1e29 libdxcompiler.so has sizes (same for clang and gcc):
- Release: 29.3MB
- MinSizeRel: 19.1MB

**Comment by gongminmin** [comment]
The pull request https://github.com/Microsoft/DirectXShaderCompiler/pull/1760 enable to sets the symbol visibility to hidden. If that goes in, the libdxcompiler.so can go down to 22M in Release build.
