### ISSUE TITLE
CMake project generation requires git.exe to be in PATH

### ISSUE THREAD

**Issue by Qartar** [Microsoft/ShaderConductor#28]
**Describe the bug**
CMake project generation requires git.exe to be in PATH in order to successfully run the `UpdateExternalLib` function defined in `External/CMakeLists.txt`. This requirement is not explicitly stated in `README.md` even though the instructions for CMake and Python both mention the PATH variable.

**To Reproduce**
1. Clone the repository
2. In a context where git is not in PATH run `Build.py` or `cmake -G ...` as instructed in `README.md`

**Expected behavior**
Expected CMake project generation to complete successfully. Instead CMake silently fails when running the git commands in `UpdateExternalLib` and generates errors later when attempting to call `add_subdirectory` on the cloned external repositories and subsequent commands on targets in those repositories.

**Additional context**
I hit this issue because I have git installed into the PATH of Git Bash for Windows only and tried to generate the project files in the developer command prompt because of an [issue with CMake and Visual Studio 2019](https://developercommunity.visualstudio.com/content/problem/399774/visual-studio-2019-preview-1-running-cmake-on-comm.html).

Not sure why git submodules aren't being used for this step.

**Comment by gongminmin** [comment]
Thanks for your report. I'll add a find git to CMake, and mention the path in readme.

**Comment by ohhmm** [comment]
Also ensuring git in path would be nice too
