### ISSUE TITLE
Vulkan descriptor shifting

### ISSUE THREAD

**Issue by amerkoleci** [microsoft/ShaderConductor#37]
**Is your feature request related to a problem? Please describe.**
Its not a problem but probably good improvements when porting shaders to vulkan backend.

**Describe the solution you'd like**
Add the missing -fvk-{b|s|t|u}-shift options (https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst).

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by klajntib** [comment]
I second this. 

For now, I've just added a new member 'compilerArgs' to SourceDesc so they get passed to DXC. If this is enough, I can do a PR, otherwise it can be formally added to Options I guess, but it might be overkill.
