### ISSUE TITLE
Static Library support

### ISSUE THREAD

**Issue by TheRealSmolt** [microsoft/ShaderConductor#46]
**Is your feature request related to a problem? Please describe.**
If I want to create a portable tool that has shader conversion support, or if I want to add the ability to generate shader code to a library, I need to worry about the DLLs.

**Describe the solution you'd like**
Use of BUILD_SHARED_LIBS in cmake or something. Whatever is easiest to implment.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gongminmin** [comment]
However, dxcompiler is DLL, which can't be changed. Even if ShaderConductor is lib, you still need to move DLLs. The down side of lib is you need link 6 other libs from SPIRV-Cross into every exes, instead of just 1.
